### ISSUE TITLE
JSON configuration persistency

### ISSUE THREAD

**Issue by PetrJakes** [awilliams/wifi-presence#11]
It looks to me JSON configuration is not persistent.
According to my tests it is necessary to publish JSON configuration to the config topic (<mqtt.prefix>/config) every time OpenWrt is rebooted.
Am I missing something?

My configuration:
Model: TP-Link TL-WR2543N/ND
Architecture: Atheros AR7242 rev 1
Firmware Version: OpenWrt 19.07.8 r11364-ef56c85848 / LuCI openwrt-19.07 branch git-21.189.23240-7b931da
Kernel Version:4.14.241
wifi-presence (0.1.1-1)

**Comment by awilliams** [comment]
Thank you @PetrJakes for the report. 

As you've described, the configuration in MQTT must be published with `retain` in order for it to persist. I will improve the README to make this more apparent.

It sounds as if your MQTT broker does not persist messages after restarts. Maybe there's a configuration setting to change this? 

I use mosquitto MQTT broker and have these two lines in my config:
```
persistence true
persistence_location /mnt/mosquitto/data/
```

And since I run mosquitto as a Docker container, I mount the persistence_location to my local host:

```
docker run \
        --rm \
        -v /etc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf \
        -v /mnt/mosquitto:/mnt/mosquitto \
        eclipse-mosquitto
```

**Comment by PetrJakes** [comment]
I have Mosquitto MQTT broker as well.
I have checked `mosquitto.conf` and persistence is set to the `true` by default, so no further action is required if the JSON configuration is published as `retain`.
Thank you for your help.
